### ISSUE TITLE
Support for postfix "if" and "unless"

### ISSUE THREAD

**Issue by janko** [AndrewRadev/vim-eco#1]
Hello. First I want to thank you for this plugin, I write eco occasionally, and this is of great use to me.

It would be really cool if you added the postfix "if" and "unless" syntax:

``` erb
<%= "value" if someCondition() %>
```

Currently it is even highlighted red, but Sam Stephenson said that the postfix syntax works fine.

Thank you

**Comment by AndrewRadev** [comment]
Ah, my bad, I added the error highlighting, but I hadn't taken into account postfix if/for clauses. I've pushed a fix to master, could you check it out and let me know if it works alright?

**Comment by janko** [comment]
Great, it works now :)

Could I ask you one more thing? Could you also syntax highlight CoffeeScript's ternary form?

``` erb
<% if condition then doSomething() else doSomethingElse() %>
```

As you know, CoffeeScript doesn't support the ternary form in the standard form, but rather this one.

**Comment by AndrewRadev** [comment]
Hmm, this one seems trickier. For now, I've disabled the colon error highlighting altogether, until I figure it out. This should fix the problem, but I'll leave the issue open until I can figure out the missing colon highlighting (or give up).

**Comment by janko** [comment]
Thank you :)

**Comment by janko** [comment]
Actually, this commit fixed it, the ternary operator is now properly highlighted. Thank you very much!

**Comment by AndrewRadev** [comment]
Yes, I did realize it would fix it, the problem was that I was trying to highlight code with missing `:` at the end, and I now disabled it. More important to highlight `if`s correctly than this check, anyway :).

I'll try to get the colon errors back at some point, so if you see related bugs, do reopen the issue (or open a new one).

**Comment by AndrewRadev** [comment]
For the record, I've reenabled error highlighting, hopefully without regressions on this issue. However, if you update soon and notice issues, let me know.

**Comment by janko** [comment]
Thank you, I will let you know.
