### ISSUE TITLE
"else if" indents twice

### ISSUE THREAD

**Issue by janko** [AndrewRadev/vim-eco#2]
In the following construct:

``` erb
<% if something: %>
  # ...
<% else if somethingElse: %>
  # ...
<% end %>
```

When I go in the new line after the `else if`, it does a double indent. It would be great if this plugin recognised this kind of expression.

**Comment by AndrewRadev** [comment]
Sorry it took so long to respond. I'm not sure how I missed this issue.

The issue seems to be caused by the newest HTML indent (which isn't that new at this point, I guess). I've pushed a workaround that should fix the issue. Could you check it out and let me know if it works for you?

**Comment by janko** [comment]
Thanks! It works now :)
