### ISSUE TITLE
No syntax highlighting for coffeescript

### ISSUE THREAD

**Issue by BrandonMathis** [AndrewRadev/vim-eco#4]
My html is getting colored but not my coffeescript. 

vimrc

```
set nocompatible              " be iMproved, required

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle "kchmck/vim-coffee-script"
Bundle "AndrewRadev/vim-eco"

syntax enable
filetype plugin indent on
```

coffeescript files are highlighted fine. 

Is this possibly a vim 7.4 issue?

**Comment by AndrewRadev** [comment]
It seems like there was a slight change in the coffeescript plugin that I hadn't noticed. I just pushed a commit that seems to fix the issue on my installation. Could you try it out and let me know if it works?

**Comment by BrandonMathis** [comment]
Thanks @AndrewRadev! Works great
