### ISSUE TITLE
Can't open file syntax/coffee.vim

### ISSUE THREAD

**Issue by nozpheratu** [AndrewRadev/vim-eco#5]
Seems it's running into an error on line [45](https://github.com/AndrewRadev/vim-eco/blob/master/syntax/eco.vim#L45) of the eco.vim syntax file. Seems to be missing a file?

**Comment by AndrewRadev** [comment]
The plugin requires the [vim-coffee-script](https://github.com/kchmck/vim-coffee-script) plugin in order to work. If you install that one, it should work out.

**Comment by nozpheratu** [comment]
@AndrewRadev  Thanks, missed that dependency bit in the readme.
